
PARALLEL_BUILD=4

OCAML_VERSION=4.00.0
CAMLP5_VERSION=6.06
FINDLIB_VERSION=1.3.3
GTK_VERSION=2.22.0
LABLGTK_VERSION=2.14.2
COQ_VERSION=8.4
SSR_VERSION=1.4

# OCAML_ROOT=C:/ocamlmgw-${OCAML_VERSION}
OCAML_ROOT=C:/ocamlmgw
GTK_ROOT=/cygdrive/c/gtk
COQ_ROOT=C:/coq-${COQ_VERSION}
NSIS_ROOT="/cygdrive/c/Program Files (x86)/NSIS/Unicode"

